/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thegreatexpansion.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.thegreatexpansion.block.*;
import net.mcreator.thegreatexpansion.TheGreatExpansionMod;

public class TheGreatExpansionModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(TheGreatExpansionMod.MODID);
	public static final DeferredBlock<Block> BAUXITE;
	public static final DeferredBlock<Block> CASSITERITE_ORE;
	public static final DeferredBlock<Block> GALENA_ORE;
	public static final DeferredBlock<Block> ILMENITE_ORE;
	public static final DeferredBlock<Block> CINNABAR_ORE;
	public static final DeferredBlock<Block> CRUSHER;
	public static final DeferredBlock<Block> STEEL_FRAME;
	public static final DeferredBlock<Block> MACHINE_FRAME;
	public static final DeferredBlock<Block> CRUDE_OIL;
	public static final DeferredBlock<Block> REFINERY;
	public static final DeferredBlock<Block> ASPHALT;
	public static final DeferredBlock<Block> FILLER;
	public static final DeferredBlock<Block> PACKED_SAND;
	public static final DeferredBlock<Block> PACKED_SAND_STAIRS;
	public static final DeferredBlock<Block> PACKED_SAND_BRICKS;
	public static final DeferredBlock<Block> PACKED_SAND_BRICK_STAIRS;
	public static final DeferredBlock<Block> ASPHALT_SLABS;
	public static final DeferredBlock<Block> ASPHALT_STAIRS;
	public static final DeferredBlock<Block> AQUALITH_ORE;
	public static final DeferredBlock<Block> AQUALITH_BLOCK;
	public static final DeferredBlock<Block> PALO_LOG;
	public static final DeferredBlock<Block> PALO_WOOD;
	public static final DeferredBlock<Block> PALO_PLANKS;
	public static final DeferredBlock<Block> PALO_LEAVES;
	public static final DeferredBlock<Block> PALO_STAIRS;
	public static final DeferredBlock<Block> PALO_SLAB;
	public static final DeferredBlock<Block> PALO_FENCE;
	public static final DeferredBlock<Block> PALO_FENCE_GATE;
	public static final DeferredBlock<Block> PALO_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PALO_BUTTON;
	public static final DeferredBlock<Block> REINFORCED_CHEST;
	public static final DeferredBlock<Block> PRESSURE_COOKER;
	public static final DeferredBlock<Block> PROPANE_GENERATOR;
	public static final DeferredBlock<Block> PALO_SAPLING;
	public static final DeferredBlock<Block> JEWLERY_WORKBENCH;
	public static final DeferredBlock<Block> SAND_VAULT;
	public static final DeferredBlock<Block> COBBLESTONE_PILLAR;
	public static final DeferredBlock<Block> COBBLESTONE_PILLAR_BASE;
	public static final DeferredBlock<Block> ALPHA_2_STATUE;
	public static final DeferredBlock<Block> COBBLESTONE_PILLAR_TOPPER;
	public static final DeferredBlock<Block> COBBLESTONE_PILLAR_T_SECTION;
	public static final DeferredBlock<Block> COBBLESTONE_PILLAR_3_WAY;
	public static final DeferredBlock<Block> COBBLESTONE_PILLAR_4_WAY;
	public static final DeferredBlock<Block> COBBLESTONE_SIDE_PILLAR;
	public static final DeferredBlock<Block> COBBLESTONE_SIDE_PILLAR_3_WAY;
	public static final DeferredBlock<Block> COBBLESTONE_SIDE_PILLAR_4_WAY;
	public static final DeferredBlock<Block> ICE_BRICKS;
	public static final DeferredBlock<Block> ICE_BRICK_STAIRS;
	public static final DeferredBlock<Block> ICE_BRICK_SLABS;
	public static final DeferredBlock<Block> ICE_BRICK_FENCE;
	public static final DeferredBlock<Block> ICE_BRICK_WALL;
	public static final DeferredBlock<Block> ICE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> ICE_BRICK_DOOR;
	public static final DeferredBlock<Block> ICE_BRICK_FENCEGATE;
	public static final DeferredBlock<Block> ICE_CUTTER;
	public static final DeferredBlock<Block> BIG_SNOWMAN;
	public static final DeferredBlock<Block> MEDIUM_SNOWMAN;
	public static final DeferredBlock<Block> SMALL_SNOWMAN;
	public static final DeferredBlock<Block> SNOW_LILY;
	public static final DeferredBlock<Block> ICE_BLOCK;
	public static final DeferredBlock<Block> ICE_BLOCK_STAIRS;
	public static final DeferredBlock<Block> ICE_BLOCK_SLABS;
	public static final DeferredBlock<Block> ICE_BLOCK_FENCE;
	public static final DeferredBlock<Block> ICE_BLOCK_WALL;
	public static final DeferredBlock<Block> ICE_BLOCK_TRAPDOOR;
	public static final DeferredBlock<Block> ICE_BLOCK_DOOR;
	public static final DeferredBlock<Block> ICE_BLOCK_FENCEGATE;
	public static final DeferredBlock<Block> SNOWDROP;
	public static final DeferredBlock<Block> HELLEBORE;
	public static final DeferredBlock<Block> WINTERBERRY;
	public static final DeferredBlock<Block> GERMINATION_TANK;
	public static final DeferredBlock<Block> PERMAFROST;
	public static final DeferredBlock<Block> PERMAFROST_IRON_ORE;
	public static final DeferredBlock<Block> REINFORCED_PERMAFROST;
	public static final DeferredBlock<Block> CRYONITE_ORE;
	public static final DeferredBlock<Block> INDUCTION_FURNACE;
	public static final DeferredBlock<Block> OMEGA_CRAFTING_TABLE;
	public static final DeferredBlock<Block> LEAD_BLOCK;
	public static final DeferredBlock<Block> COMPRESSED_LEAD_BLOCK;
	public static final DeferredBlock<Block> CAPSULATOR;
	public static final DeferredBlock<Block> ENRICHMENT_FRAME;
	public static final DeferredBlock<Block> REINFORCED_GLASS;
	static {
		BAUXITE = REGISTRY.register("bauxite", BauxiteBlock::new);
		CASSITERITE_ORE = REGISTRY.register("cassiterite_ore", CassiteriteOreBlock::new);
		GALENA_ORE = REGISTRY.register("galena_ore", GalenaOreBlock::new);
		ILMENITE_ORE = REGISTRY.register("ilmenite_ore", IlmeniteOreBlock::new);
		CINNABAR_ORE = REGISTRY.register("cinnabar_ore", CinnabarOreBlock::new);
		CRUSHER = REGISTRY.register("crusher", CrusherBlock::new);
		STEEL_FRAME = REGISTRY.register("steel_frame", SteelFrameBlock::new);
		MACHINE_FRAME = REGISTRY.register("machine_frame", MachineFrameBlock::new);
		CRUDE_OIL = REGISTRY.register("crude_oil", CrudeOilBlock::new);
		REFINERY = REGISTRY.register("refinery", RefineryBlock::new);
		ASPHALT = REGISTRY.register("asphalt", AsphaltBlock::new);
		FILLER = REGISTRY.register("filler", FillerBlock::new);
		PACKED_SAND = REGISTRY.register("packed_sand", PackedSandBlock::new);
		PACKED_SAND_STAIRS = REGISTRY.register("packed_sand_stairs", PackedSandStairsBlock::new);
		PACKED_SAND_BRICKS = REGISTRY.register("packed_sand_bricks", PackedSandBricksBlock::new);
		PACKED_SAND_BRICK_STAIRS = REGISTRY.register("packed_sand_brick_stairs", PackedSandBrickStairsBlock::new);
		ASPHALT_SLABS = REGISTRY.register("asphalt_slabs", AsphaltSlabsBlock::new);
		ASPHALT_STAIRS = REGISTRY.register("asphalt_stairs", AsphaltStairsBlock::new);
		AQUALITH_ORE = REGISTRY.register("aqualith_ore", AqualithOreBlock::new);
		AQUALITH_BLOCK = REGISTRY.register("aqualith_block", AqualithBlockBlock::new);
		PALO_LOG = REGISTRY.register("palo_log", PaloLogBlock::new);
		PALO_WOOD = REGISTRY.register("palo_wood", PaloWoodBlock::new);
		PALO_PLANKS = REGISTRY.register("palo_planks", PaloPlanksBlock::new);
		PALO_LEAVES = REGISTRY.register("palo_leaves", PaloLeavesBlock::new);
		PALO_STAIRS = REGISTRY.register("palo_stairs", PaloStairsBlock::new);
		PALO_SLAB = REGISTRY.register("palo_slab", PaloSlabBlock::new);
		PALO_FENCE = REGISTRY.register("palo_fence", PaloFenceBlock::new);
		PALO_FENCE_GATE = REGISTRY.register("palo_fence_gate", PaloFenceGateBlock::new);
		PALO_PRESSURE_PLATE = REGISTRY.register("palo_pressure_plate", PaloPressurePlateBlock::new);
		PALO_BUTTON = REGISTRY.register("palo_button", PaloButtonBlock::new);
		REINFORCED_CHEST = REGISTRY.register("reinforced_chest", ReinforcedChestBlock::new);
		PRESSURE_COOKER = REGISTRY.register("pressure_cooker", PressureCookerBlock::new);
		PROPANE_GENERATOR = REGISTRY.register("propane_generator", PropaneGeneratorBlock::new);
		PALO_SAPLING = REGISTRY.register("palo_sapling", PaloSaplingBlock::new);
		JEWLERY_WORKBENCH = REGISTRY.register("jewlery_workbench", JewleryWorkbenchBlock::new);
		SAND_VAULT = REGISTRY.register("sand_vault", SandVaultBlock::new);
		COBBLESTONE_PILLAR = REGISTRY.register("cobblestone_pillar", CobblestonePillarBlock::new);
		COBBLESTONE_PILLAR_BASE = REGISTRY.register("cobblestone_pillar_base", CobblestonePillarBaseBlock::new);
		ALPHA_2_STATUE = REGISTRY.register("alpha_2_statue", Alpha2StatueBlock::new);
		COBBLESTONE_PILLAR_TOPPER = REGISTRY.register("cobblestone_pillar_topper", CobblestonePillarTopperBlock::new);
		COBBLESTONE_PILLAR_T_SECTION = REGISTRY.register("cobblestone_pillar_t_section", CobblestonePillarTSectionBlock::new);
		COBBLESTONE_PILLAR_3_WAY = REGISTRY.register("cobblestone_pillar_3_way", CobblestonePillar3WayBlock::new);
		COBBLESTONE_PILLAR_4_WAY = REGISTRY.register("cobblestone_pillar_4_way", CobblestonePillar4WayBlock::new);
		COBBLESTONE_SIDE_PILLAR = REGISTRY.register("cobblestone_side_pillar", CobblestoneSidePillarBlock::new);
		COBBLESTONE_SIDE_PILLAR_3_WAY = REGISTRY.register("cobblestone_side_pillar_3_way", CobblestoneSidePillar3WayBlock::new);
		COBBLESTONE_SIDE_PILLAR_4_WAY = REGISTRY.register("cobblestone_side_pillar_4_way", CobblestoneSidePillar4WayBlock::new);
		ICE_BRICKS = REGISTRY.register("ice_bricks", IceBricksBlock::new);
		ICE_BRICK_STAIRS = REGISTRY.register("ice_brick_stairs", IceBrickStairsBlock::new);
		ICE_BRICK_SLABS = REGISTRY.register("ice_brick_slabs", IceBrickSlabsBlock::new);
		ICE_BRICK_FENCE = REGISTRY.register("ice_brick_fence", IceBrickFenceBlock::new);
		ICE_BRICK_WALL = REGISTRY.register("ice_brick_wall", IceBrickWallBlock::new);
		ICE_BRICK_TRAPDOOR = REGISTRY.register("ice_brick_trapdoor", IceBrickTrapdoorBlock::new);
		ICE_BRICK_DOOR = REGISTRY.register("ice_brick_door", IceBrickDoorBlock::new);
		ICE_BRICK_FENCEGATE = REGISTRY.register("ice_brick_fencegate", IceBrickFencegateBlock::new);
		ICE_CUTTER = REGISTRY.register("ice_cutter", IceCutterBlock::new);
		BIG_SNOWMAN = REGISTRY.register("big_snowman", BigSnowmanBlock::new);
		MEDIUM_SNOWMAN = REGISTRY.register("medium_snowman", MediumSnowmanBlock::new);
		SMALL_SNOWMAN = REGISTRY.register("small_snowman", SmallSnowmanBlock::new);
		SNOW_LILY = REGISTRY.register("snow_lily", SnowLilyBlock::new);
		ICE_BLOCK = REGISTRY.register("ice_block", IceBlockBlock::new);
		ICE_BLOCK_STAIRS = REGISTRY.register("ice_block_stairs", IceBlockStairsBlock::new);
		ICE_BLOCK_SLABS = REGISTRY.register("ice_block_slabs", IceBlockSlabsBlock::new);
		ICE_BLOCK_FENCE = REGISTRY.register("ice_block_fence", IceBlockFenceBlock::new);
		ICE_BLOCK_WALL = REGISTRY.register("ice_block_wall", IceBlockWallBlock::new);
		ICE_BLOCK_TRAPDOOR = REGISTRY.register("ice_block_trapdoor", IceBlockTrapdoorBlock::new);
		ICE_BLOCK_DOOR = REGISTRY.register("ice_block_door", IceBlockDoorBlock::new);
		ICE_BLOCK_FENCEGATE = REGISTRY.register("ice_block_fencegate", IceBlockFencegateBlock::new);
		SNOWDROP = REGISTRY.register("snowdrop", SnowdropBlock::new);
		HELLEBORE = REGISTRY.register("hellebore", HelleboreBlock::new);
		WINTERBERRY = REGISTRY.register("winterberry", WinterberryBlock::new);
		GERMINATION_TANK = REGISTRY.register("germination_tank", GerminationTankBlock::new);
		PERMAFROST = REGISTRY.register("permafrost", PermafrostBlock::new);
		PERMAFROST_IRON_ORE = REGISTRY.register("permafrost_iron_ore", PermafrostIronOreBlock::new);
		REINFORCED_PERMAFROST = REGISTRY.register("reinforced_permafrost", ReinforcedPermafrostBlock::new);
		CRYONITE_ORE = REGISTRY.register("cryonite_ore", CryoniteOreBlock::new);
		INDUCTION_FURNACE = REGISTRY.register("induction_furnace", InductionFurnaceBlock::new);
		OMEGA_CRAFTING_TABLE = REGISTRY.register("omega_crafting_table", OmegaCraftingTableBlock::new);
		LEAD_BLOCK = REGISTRY.register("lead_block", LeadBlockBlock::new);
		COMPRESSED_LEAD_BLOCK = REGISTRY.register("compressed_lead_block", CompressedLeadBlockBlock::new);
		CAPSULATOR = REGISTRY.register("capsulator", CapsulatorBlock::new);
		ENRICHMENT_FRAME = REGISTRY.register("enrichment_frame", EnrichmentFrameBlock::new);
		REINFORCED_GLASS = REGISTRY.register("reinforced_glass", ReinforcedGlassBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}